///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyTest1
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The BasicDemoRecord recording.
    /// </summary>
    [TestModule("d4838334-b143-4c26-b218-6ebad36a616d", ModuleType.Recording, 1)]
    public partial class BasicDemoRecord : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyTest1Repository repository.
        /// </summary>
        public static MyTest1Repository repo = MyTest1Repository.Instance;

        static BasicDemoRecord instance = new BasicDemoRecord();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public BasicDemoRecord()
        {
            telnum = "05352826962";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static BasicDemoRecord Instance
        {
            get { return instance; }
        }

#region Variables

        string _telnum;

        /// <summary>
        /// Gets or sets the value of variable telnum.
        /// </summary>
        [TestVariable("acbb35c7-716f-4305-9521-f1aba36c56fb")]
        public string telnum
        {
            get { return _telnum; }
            set { _telnum = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Run mobile app 'com.sodexo.flexogift' on device " + Ranorex.Core.Remoting.RemoteServiceLocator.GetCurrentDeviceName() + ".", new RecordItemIndex(0));
            Host.Local.RunMobileApp(Ranorex.Core.Remoting.RemoteServiceLocator.GetCurrentDeviceName(), "com.sodexo.flexogift", true);
            Delay.Milliseconds(3500);
            
            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to '$telnum' on item 'ComSodexoFlexogift.Frame.ComFacebookReactViewsTextinputReact'.", repo.ComSodexoFlexogift.Frame.ComFacebookReactViewsTextinputReactInfo, new RecordItemIndex(1));
            repo.ComSodexoFlexogift.Frame.ComFacebookReactViewsTextinputReact.Element.SetAttributeValue("Text", telnum);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComSodexoFlexogift.Frame.GirişYapKayıtOl' at Center", repo.ComSodexoFlexogift.Frame.GirişYapKayıtOlInfo, new RecordItemIndex(2));
            repo.ComSodexoFlexogift.Frame.GirişYapKayıtOl.Touch();
            Delay.Milliseconds(300);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating ContainsImage (Screenshot: 'Screenshot1' with region {X=0,Y=0,Width=986,Height=69}) on item 'ComSodexoFlexogift.Frame.GirişYap'.", repo.ComSodexoFlexogift.Frame.GirişYapInfo, new RecordItemIndex(3));
            Validate.ContainsImage(repo.ComSodexoFlexogift.Frame.GirişYapInfo, GirişYap_Screenshot1, GirişYap_Screenshot1_Options);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        CompressedImage GirişYap_Screenshot1
        { get { return repo.ComSodexoFlexogift.Frame.GirişYapInfo.GetScreenshot1(new Rectangle(0, 0, 986, 69)); } }

        /// <summary>
        /// DO NOT REFERENCE THIS CODE  - auto generated
        /// </summary>
        Imaging.FindOptions GirişYap_Screenshot1_Options
        { get { return Imaging.FindOptions.Default; } }

#endregion
    }
#pragma warning restore 0436
}
